#!/usr/bin/bash

#SBATCH --ntasks=1 --cpus-per-task=8
#SBATCH --time=30:30:00
#SBATCH --job-name=a_a
#SBATCH --mail-user=your_email@institution.edu
#BATCH --mail-type=FAIL
#SBATCH -A your_hpc_account
#SBATCH --cluster genius


# source your HPC environment here 
source activate your_env_name
# cd to your pipeline directory
set_thresh.py -g A -i $VSC_DATA/aspergillus -d output/genus_A_d_window_6.pkl -l info -a C -t '(43200, 50000, 1800)' -s '[0.0, 1.0, 0.01]' -n posaco_debug_ATU_VMEs -m "[2]"
