#!/usr/bin/bash

#SBATCH --ntasks=1 --cpus-per-task=8
#SBATCH --time=30:30:00
#SBATCH --job-name=a_a
#SBATCH --mail-user=klaasdewaele@gmail.com
#BATCH --mail-type=FAIL
#SBATCH -A lp_ea_group

source /user/leuven/348/vsc34807/.bashrc 
source activate ocelloscope
cd $VSC_DATA/miniconda3/envs/ocelloscope/bin/
set_thresh.py -g A -i $VSC_DATA/aspergillus -d $VSC_SCRATCH/oCelloscope/genus_A_d_window_6.pkl -l info -a E -t '(80000, 100000, 3600)' -s '[0.0, 1.0, 0.01]' -n isavu_debug_VME_jump_80000 -m "[2]"
