#!/usr/bin/bash

#SBATCH --ntasks=1 --cpus-per-task=8
#SBATCH --time=30:30:00
#SBATCH --job-name=a_a
#SBATCH --mail-user=klaasdewaele@gmail.com
#BATCH --mail-type=FAIL
#SBATCH -A lp_ea_group

source /user/leuven/348/vsc34807/.bashrc 
source activate ocelloscope
cd $VSC_DATA/miniconda3/envs/ocelloscope/bin/
set_thresh.py -g C -i $VSC_DATA/candida -d $VSC_SCRATCH/oCelloscope/genus_C_d_window_6.pkl -l info -a A -t '(18000, 87000, 1800)' -s '[0.0, 1.0, 0.01]' -n 27_jun_prop_m2 -m "[2]"
