#!/data/leuven/348/vsc34807/miniconda3/bin/python

import pandas as pd
import importlib
import pprint
# Read the Excel file and create a dictionary with the Old_name column as the keys
# and the Final_new_name column as the values
df = pd.read_excel("/Users/klaasdewaele/Google Drive/oCelloscope/names_conversion.xlsx")
name_conversion = df.set_index('Old_name')['Final_new_name_3'].to_dict()
# Import the dictionaries from the dictionaries.py file
import dictionaries

print(f'\nName conversion dict \n: {name_conversion}\n')

dicts_to_convert = [dictionaries.MIC_dict_A, dictionaries.MIC_dict_C, dictionaries.species_dict_A_old, dictionaries.species_dict_C_old]

dict_names = ['MIC_dict_A', 'MIC_dict_C', 'species_dict_A', 'species_dict_C']
# Loop through the list of dictionaries and create new dictionaries where the keys
# are replaced with the values from the name_conversion dictionary
converted_dicts = []
for index, old_dict in enumerate(dicts_to_convert):
    #print(f'old dict: {old_dict}')
    new_dict = {}
    for key, value in old_dict.items():
        if key in name_conversion:
            #print(f'\n\nold_dict: {old_dict}')
            new_key = name_conversion[key]
            new_dict[new_key] = value
        else:
            new_dict[key] = value
    converted_dicts.append((dict_names[index], new_dict))

for diction in converted_dicts:
    print(f'{diction[0]} = {diction[1]}')
    print('\n')
#pprint.pprint(f'converted_dicts: {converted_dicts}')
# The converted dictionaries are now stored in the converted_dicts list
